cloud:
  aws:
    credentials:
      access-key: AKIAVKDXPKRH7XVPVB52
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: netcrackerfileupload141647


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
